import swaggerAutogen from 'swagger-autogen';

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Token Generator API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    definitions: {
        User: {
            $id: "1",
            $site: "datawarehouse"
        }
    }
}


swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    import("./index.js");          // Your project's root file
})